# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
baseURL = "https://lykienhuy.github.io/workshop/"
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Xóa cấu hình cache có thể gây vấn đề
# [caches]
#   [caches.images]
#     dir = ':cacheDir/images'

# Cấu hình params
[params]
  # Đảm bảo đường dẫn hình ảnh chính xác
  relativeURLs = true
  uglyURLs = false
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "huyly520@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Automated Security Scanning System using GuardDuty and Lambda function"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Automated Security Scanning System using GuardDuty and Lambda function"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

